/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.3.1.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class GameClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getGames(): Observable<GameListingDto[] | null> {
        let url_ = this.baseUrl + "/api/Game";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetGames(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetGames(<any>response_);
                } catch (e) {
                    return <Observable<GameListingDto[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GameListingDto[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetGames(response: HttpResponseBase): Observable<GameListingDto[] | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GameListingDto.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GameListingDto[] | null>(<any>null);
    }

    createGame(game: GameUpdateDto): Observable<number> {
        let url_ = this.baseUrl + "/api/Game";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(game);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateGame(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateGame(<any>response_);
                } catch (e) {
                    return <Observable<number>><any>_observableThrow(e);
                }
            } else
                return <Observable<number>><any>_observableThrow(response_);
        }));
    }

    protected processCreateGame(response: HttpResponseBase): Observable<number> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number>(<any>null);
    }

    updateGame(game: GameUpdateDto): Observable<void> {
        let url_ = this.baseUrl + "/api/Game";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(game);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateGame(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateGame(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processUpdateGame(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    getGame(id: number): Observable<GameDetailDto | null> {
        let url_ = this.baseUrl + "/api/Game/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetGame(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetGame(<any>response_);
                } catch (e) {
                    return <Observable<GameDetailDto | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GameDetailDto | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetGame(response: HttpResponseBase): Observable<GameDetailDto | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GameDetailDto.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : <any>null;
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GameDetailDto | null>(<any>null);
    }

    deleteGame(id: number): Observable<void> {
        let url_ = this.baseUrl + "/api/Game/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteGame(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteGame(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processDeleteGame(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    createMultipleGames(games: GameUpdateDto[]): Observable<number> {
        let url_ = this.baseUrl + "/api/Game/CreateMany";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(games);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateMultipleGames(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateMultipleGames(<any>response_);
                } catch (e) {
                    return <Observable<number>><any>_observableThrow(e);
                }
            } else
                return <Observable<number>><any>_observableThrow(response_);
        }));
    }

    protected processCreateMultipleGames(response: HttpResponseBase): Observable<number> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number>(<any>null);
    }
}

@Injectable()
export class GraphClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    get(): Observable<GraphDto[] | null> {
        let url_ = this.baseUrl + "/api/Graph";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGet(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGet(<any>response_);
                } catch (e) {
                    return <Observable<GraphDto[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GraphDto[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGet(response: HttpResponseBase): Observable<GraphDto[] | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GraphDto.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GraphDto[] | null>(<any>null);
    }
}

@Injectable()
export class LeaderboardClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getLeaderboard(team: Team | undefined, timescale: Timescale | undefined, noOfPlayers: number | undefined, asOfWhen: number | undefined): Observable<LeaderboardDto[] | null> {
        let url_ = this.baseUrl + "/api/Leaderboard?";
        if (team === null)
            throw new Error("The parameter 'team' cannot be null.");
        else if (team !== undefined)
            url_ += "Team=" + encodeURIComponent("" + team) + "&"; 
        if (timescale === null)
            throw new Error("The parameter 'timescale' cannot be null.");
        else if (timescale !== undefined)
            url_ += "Timescale=" + encodeURIComponent("" + timescale) + "&"; 
        if (noOfPlayers === null)
            throw new Error("The parameter 'noOfPlayers' cannot be null.");
        else if (noOfPlayers !== undefined)
            url_ += "NoOfPlayers=" + encodeURIComponent("" + noOfPlayers) + "&"; 
        if (asOfWhen === null)
            throw new Error("The parameter 'asOfWhen' cannot be null.");
        else if (asOfWhen !== undefined)
            url_ += "AsOfWhen=" + encodeURIComponent("" + asOfWhen) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetLeaderboard(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetLeaderboard(<any>response_);
                } catch (e) {
                    return <Observable<LeaderboardDto[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<LeaderboardDto[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetLeaderboard(response: HttpResponseBase): Observable<LeaderboardDto[] | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(LeaderboardDto.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData400 && resultData400.constructor === Array) {
                result400 = [] as any;
                for (let item of resultData400)
                    result400!.push(LeaderboardDto.fromJS(item));
            }
            return throwException("A server error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<LeaderboardDto[] | null>(<any>null);
    }

    getGameLeaderboard(): Observable<GameOverviewDto[] | null> {
        let url_ = this.baseUrl + "/api/Leaderboard/GameLeaderboard";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetGameLeaderboard(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetGameLeaderboard(<any>response_);
                } catch (e) {
                    return <Observable<GameOverviewDto[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GameOverviewDto[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetGameLeaderboard(response: HttpResponseBase): Observable<GameOverviewDto[] | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GameOverviewDto.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GameOverviewDto[] | null>(<any>null);
    }

    getDaySummary(daysAgo: number | undefined): Observable<GameListDto | null> {
        let url_ = this.baseUrl + "/api/Leaderboard/DaySummary?";
        if (daysAgo === null)
            throw new Error("The parameter 'daysAgo' cannot be null.");
        else if (daysAgo !== undefined)
            url_ += "daysAgo=" + encodeURIComponent("" + daysAgo) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetDaySummary(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetDaySummary(<any>response_);
                } catch (e) {
                    return <Observable<GameListDto | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GameListDto | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetDaySummary(response: HttpResponseBase): Observable<GameListDto | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GameListDto.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GameListDto | null>(<any>null);
    }
}

@Injectable()
export class PlayerClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getPlayers(): Observable<PlayerListingDto[] | null> {
        let url_ = this.baseUrl + "/api/Player";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPlayers(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPlayers(<any>response_);
                } catch (e) {
                    return <Observable<PlayerListingDto[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<PlayerListingDto[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetPlayers(response: HttpResponseBase): Observable<PlayerListingDto[] | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PlayerListingDto.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PlayerListingDto[] | null>(<any>null);
    }

    createPlayer(player: PlayerUpdateDto): Observable<number> {
        let url_ = this.baseUrl + "/api/Player";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(player);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreatePlayer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreatePlayer(<any>response_);
                } catch (e) {
                    return <Observable<number>><any>_observableThrow(e);
                }
            } else
                return <Observable<number>><any>_observableThrow(response_);
        }));
    }

    protected processCreatePlayer(response: HttpResponseBase): Observable<number> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number>(<any>null);
    }

    updatePlayer(player: PlayerUpdateDto): Observable<void> {
        let url_ = this.baseUrl + "/api/Player";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(player);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdatePlayer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdatePlayer(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processUpdatePlayer(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    getPlayer(id: number): Observable<PlayerDetailDto | null> {
        let url_ = this.baseUrl + "/api/Player/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPlayer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPlayer(<any>response_);
                } catch (e) {
                    return <Observable<PlayerDetailDto | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<PlayerDetailDto | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetPlayer(response: HttpResponseBase): Observable<PlayerDetailDto | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? PlayerDetailDto.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : <any>null;
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PlayerDetailDto | null>(<any>null);
    }

    deletePlayer(id: number): Observable<void> {
        let url_ = this.baseUrl + "/api/Player/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeletePlayer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeletePlayer(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processDeletePlayer(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }
}

export class GameListingDto implements IGameListingDto {
    id!: number;
    date!: Date;
    resistanceWin!: boolean;
    players?: string[] | undefined;

    constructor(data?: IGameListingDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.date = data["date"] ? new Date(data["date"].toString()) : <any>undefined;
            this.resistanceWin = data["resistanceWin"];
            if (data["players"] && data["players"].constructor === Array) {
                this.players = [] as any;
                for (let item of data["players"])
                    this.players!.push(item);
            }
        }
    }

    static fromJS(data: any): GameListingDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameListingDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["resistanceWin"] = this.resistanceWin;
        if (this.players && this.players.constructor === Array) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item);
        }
        return data; 
    }
}

export interface IGameListingDto {
    id: number;
    date: Date;
    resistanceWin: boolean;
    players?: string[] | undefined;
}

export class GameDetailDto implements IGameDetailDto {
    id!: number;
    date!: Date;
    resistanceWin!: boolean;
    players?: GamePlayerDetailDto[] | undefined;

    constructor(data?: IGameDetailDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.date = data["date"] ? new Date(data["date"].toString()) : <any>undefined;
            this.resistanceWin = data["resistanceWin"];
            if (data["players"] && data["players"].constructor === Array) {
                this.players = [] as any;
                for (let item of data["players"])
                    this.players!.push(GamePlayerDetailDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GameDetailDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameDetailDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["resistanceWin"] = this.resistanceWin;
        if (this.players && this.players.constructor === Array) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IGameDetailDto {
    id: number;
    date: Date;
    resistanceWin: boolean;
    players?: GamePlayerDetailDto[] | undefined;
}

export class GamePlayerDetailDto implements IGamePlayerDetailDto {
    id!: number;
    wasResistance!: boolean;
    role!: Role;

    constructor(data?: IGamePlayerDetailDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.wasResistance = data["wasResistance"];
            this.role = data["role"];
        }
    }

    static fromJS(data: any): GamePlayerDetailDto {
        data = typeof data === 'object' ? data : {};
        let result = new GamePlayerDetailDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["wasResistance"] = this.wasResistance;
        data["role"] = this.role;
        return data; 
    }
}

export interface IGamePlayerDetailDto {
    id: number;
    wasResistance: boolean;
    role: Role;
}

export enum Role {
    None = 0, 
    Regular = 1, 
    Hunter = 2, 
    Chief = 3, 
    Dummy = 4, 
    Defector = 5, 
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.type = data["type"];
            this.title = data["title"];
            this.status = data["status"];
            this.detail = data["detail"];
            this.instance = data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data; 
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

export class GameUpdateDto implements IGameUpdateDto {
    id!: number;
    date!: Date;
    resistanceWin!: boolean;
    players!: GamePlayerUpdateDto[];

    constructor(data?: IGameUpdateDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.players = [];
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.date = data["date"] ? new Date(data["date"].toString()) : <any>undefined;
            this.resistanceWin = data["resistanceWin"];
            if (data["players"] && data["players"].constructor === Array) {
                this.players = [] as any;
                for (let item of data["players"])
                    this.players!.push(GamePlayerUpdateDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GameUpdateDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameUpdateDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["resistanceWin"] = this.resistanceWin;
        if (this.players && this.players.constructor === Array) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IGameUpdateDto {
    id: number;
    date: Date;
    resistanceWin: boolean;
    players: GamePlayerUpdateDto[];
}

export class GamePlayerUpdateDto implements IGamePlayerUpdateDto {
    id!: number;
    wasResistance!: boolean;
    role!: Role;

    constructor(data?: IGamePlayerUpdateDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.wasResistance = data["wasResistance"];
            this.role = data["role"];
        }
    }

    static fromJS(data: any): GamePlayerUpdateDto {
        data = typeof data === 'object' ? data : {};
        let result = new GamePlayerUpdateDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["wasResistance"] = this.wasResistance;
        data["role"] = this.role;
        return data; 
    }
}

export interface IGamePlayerUpdateDto {
    id: number;
    wasResistance: boolean;
    role: Role;
}

export class GraphDto implements IGraphDto {
    graphPlayers?: GraphPlayerDto[] | undefined;
    firstGameId!: number;
    lastGameId!: number;

    constructor(data?: IGraphDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["graphPlayers"] && data["graphPlayers"].constructor === Array) {
                this.graphPlayers = [] as any;
                for (let item of data["graphPlayers"])
                    this.graphPlayers!.push(GraphPlayerDto.fromJS(item));
            }
            this.firstGameId = data["firstGameId"];
            this.lastGameId = data["lastGameId"];
        }
    }

    static fromJS(data: any): GraphDto {
        data = typeof data === 'object' ? data : {};
        let result = new GraphDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.graphPlayers && this.graphPlayers.constructor === Array) {
            data["graphPlayers"] = [];
            for (let item of this.graphPlayers)
                data["graphPlayers"].push(item.toJSON());
        }
        data["firstGameId"] = this.firstGameId;
        data["lastGameId"] = this.lastGameId;
        return data; 
    }
}

export interface IGraphDto {
    graphPlayers?: GraphPlayerDto[] | undefined;
    firstGameId: number;
    lastGameId: number;
}

export class GraphPlayerDto implements IGraphPlayerDto {
    playerId!: number;
    graphPoints?: GraphPointDto[] | undefined;

    constructor(data?: IGraphPlayerDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.playerId = data["playerId"];
            if (data["graphPoints"] && data["graphPoints"].constructor === Array) {
                this.graphPoints = [] as any;
                for (let item of data["graphPoints"])
                    this.graphPoints!.push(GraphPointDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GraphPlayerDto {
        data = typeof data === 'object' ? data : {};
        let result = new GraphPlayerDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["playerId"] = this.playerId;
        if (this.graphPoints && this.graphPoints.constructor === Array) {
            data["graphPoints"] = [];
            for (let item of this.graphPoints)
                data["graphPoints"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IGraphPlayerDto {
    playerId: number;
    graphPoints?: GraphPointDto[] | undefined;
}

export class GraphPointDto implements IGraphPointDto {
    wins!: number;
    totalGames!: number;
    gameId!: number;

    constructor(data?: IGraphPointDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.wins = data["wins"];
            this.totalGames = data["totalGames"];
            this.gameId = data["gameId"];
        }
    }

    static fromJS(data: any): GraphPointDto {
        data = typeof data === 'object' ? data : {};
        let result = new GraphPointDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["wins"] = this.wins;
        data["totalGames"] = this.totalGames;
        data["gameId"] = this.gameId;
        return data; 
    }
}

export interface IGraphPointDto {
    wins: number;
    totalGames: number;
    gameId: number;
}

export class LeaderboardDto implements ILeaderboardDto {
    playerId!: number;
    initials?: string | undefined;
    wins!: number;
    totalGames!: number;

    constructor(data?: ILeaderboardDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.playerId = data["playerId"];
            this.initials = data["initials"];
            this.wins = data["wins"];
            this.totalGames = data["totalGames"];
        }
    }

    static fromJS(data: any): LeaderboardDto {
        data = typeof data === 'object' ? data : {};
        let result = new LeaderboardDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["playerId"] = this.playerId;
        data["initials"] = this.initials;
        data["wins"] = this.wins;
        data["totalGames"] = this.totalGames;
        return data; 
    }
}

export interface ILeaderboardDto {
    playerId: number;
    initials?: string | undefined;
    wins: number;
    totalGames: number;
}

export enum Team {
    None = 0, 
    Resistance = 1, 
    Spy = 2, 
}

export enum Timescale {
    AllTime = 0, 
    Last7Days = 1, 
    Last30Days = 2, 
}

export class GameOverviewDto implements IGameOverviewDto {
    resistanceWins!: number;
    totalGames!: number;

    constructor(data?: IGameOverviewDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.resistanceWins = data["resistanceWins"];
            this.totalGames = data["totalGames"];
        }
    }

    static fromJS(data: any): GameOverviewDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameOverviewDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["resistanceWins"] = this.resistanceWins;
        data["totalGames"] = this.totalGames;
        return data; 
    }
}

export interface IGameOverviewDto {
    resistanceWins: number;
    totalGames: number;
}

export class GameListDto implements IGameListDto {
    players?: string[] | undefined;
    games?: GameSummaryDto[] | undefined;

    constructor(data?: IGameListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["players"] && data["players"].constructor === Array) {
                this.players = [] as any;
                for (let item of data["players"])
                    this.players!.push(item);
            }
            if (data["games"] && data["games"].constructor === Array) {
                this.games = [] as any;
                for (let item of data["games"])
                    this.games!.push(GameSummaryDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GameListDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.players && this.players.constructor === Array) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item);
        }
        if (this.games && this.games.constructor === Array) {
            data["games"] = [];
            for (let item of this.games)
                data["games"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IGameListDto {
    players?: string[] | undefined;
    games?: GameSummaryDto[] | undefined;
}

export class GameSummaryDto implements IGameSummaryDto {
    players?: PlayerWinDto[] | undefined;

    constructor(data?: IGameSummaryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["players"] && data["players"].constructor === Array) {
                this.players = [] as any;
                for (let item of data["players"])
                    this.players!.push(PlayerWinDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GameSummaryDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameSummaryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.players && this.players.constructor === Array) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IGameSummaryDto {
    players?: PlayerWinDto[] | undefined;
}

export class PlayerWinDto implements IPlayerWinDto {
    player?: string | undefined;
    win!: boolean;

    constructor(data?: IPlayerWinDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.player = data["player"];
            this.win = data["win"];
        }
    }

    static fromJS(data: any): PlayerWinDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerWinDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["player"] = this.player;
        data["win"] = this.win;
        return data; 
    }
}

export interface IPlayerWinDto {
    player?: string | undefined;
    win: boolean;
}

export class PlayerListingDto implements IPlayerListingDto {
    id!: number;
    firstName?: string | undefined;
    surname?: string | undefined;
    initials?: string | undefined;

    constructor(data?: IPlayerListingDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.firstName = data["firstName"];
            this.surname = data["surname"];
            this.initials = data["initials"];
        }
    }

    static fromJS(data: any): PlayerListingDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerListingDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["firstName"] = this.firstName;
        data["surname"] = this.surname;
        data["initials"] = this.initials;
        return data; 
    }
}

export interface IPlayerListingDto {
    id: number;
    firstName?: string | undefined;
    surname?: string | undefined;
    initials?: string | undefined;
}

export class PlayerDetailDto implements IPlayerDetailDto {
    id!: number;
    firstName!: string;
    surname!: string;
    initials!: string;

    constructor(data?: IPlayerDetailDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.firstName = data["firstName"];
            this.surname = data["surname"];
            this.initials = data["initials"];
        }
    }

    static fromJS(data: any): PlayerDetailDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerDetailDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["firstName"] = this.firstName;
        data["surname"] = this.surname;
        data["initials"] = this.initials;
        return data; 
    }
}

export interface IPlayerDetailDto {
    id: number;
    firstName: string;
    surname: string;
    initials: string;
}

export class PlayerUpdateDto implements IPlayerUpdateDto {
    id!: number;
    firstName!: string;
    surname!: string;
    initials!: string;

    constructor(data?: IPlayerUpdateDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.firstName = data["firstName"];
            this.surname = data["surname"];
            this.initials = data["initials"];
        }
    }

    static fromJS(data: any): PlayerUpdateDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerUpdateDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["firstName"] = this.firstName;
        data["surname"] = this.surname;
        data["initials"] = this.initials;
        return data; 
    }
}

export interface IPlayerUpdateDto {
    id: number;
    firstName: string;
    surname: string;
    initials: string;
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if(result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}